### ISSUE TITLE
INFOGRAFÍA 

### ISSUE THREAD

**Issue by Rosa218** [SistemasTecTlaxiaco/infografia-de-hilos-Rosa218#2]
[¿Que es un hilo en programacion_.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Rosa218/files/6472887/Que.es.un.hilo.en.programacion_.pdf)

**Comment by Nayee123** [comment]
Calificación de la infografía: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
